
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  headers = {Content-Type = "application/manifest+json"}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = ".next"
